-- Sweep for silently-discarded query errors (2026-09-20)
--
-- Context: supabase-js RESOLVES every query with { data, error } rather than
-- rejecting. An `await` inside try/catch therefore never sees a database
-- error, and an unchecked result makes a hard failure indistinguishable from
-- "no rows". That is exactly how the Circle feed rendered "No new activity"
-- for days after are_friends() lost its EXECUTE grant.
--
-- Swept all 272 sbClient call sites in index.html. Client-side changes are in
-- the same commit; the only schema change needed was this one:
--
-- FINDING: profiles.handle had NO unique constraint. Handle uniqueness was
-- enforced solely by isHandleTaken() in the browser, so a failed lookup, a
-- race between two concurrent signups, or a direct PostgREST call could all
-- create duplicate handles. handle_aliases has a unique pkey; profiles did
-- not. Verified zero case-insensitive duplicates, then added
-- (migration unique_profile_handle_ci):
--
--   create unique index if not exists profiles_handle_lower_key
--     on public.profiles (lower(handle))
--     where handle is not null and btrim(handle) <> '';
--
-- isHandleTaken() now also fails closed when the lookup errors.

-- ── Second pass (reads), 2026-09-20 ────────────────────────────────────
-- Covered the remaining 96 unchecked reads. 110 sbCheck() call sites and 21
-- .throwOnError() chains now. No schema change was required, but two checks
-- were made against the database first, and both mattered:
--
--   * friendships has a unique (requester_id, addressee_id) index,
--     group_members is keyed on (group_id, user_id), and list_reactions has a
--     unique index on (from_user_id, list_owner_id, category, item_name,
--     emoji). So the "already exists?" reads in front of those inserts are
--     backed by the database — a failed read cannot actually duplicate a row.
--     They were still made to fail closed so a failed read surfaces as a
--     message rather than a constraint violation.
--
--   * profiles.handle was the one case with NO backing constraint; fixed in
--     migration unique_profile_handle_ci (see above).
--
-- OPEN ITEM (not addressed here): actor_not_banned() gates only 6 policies
-- across 4 tables — friendships INSERT, groups INSERT, lists INSERT/UPDATE
-- and list_item_comments INSERT/UPDATE. A banned user can still insert
-- list_reactions, list_share_invites, group_members and feedback. The client
-- checkIfBanned() does not close this: it fails open on a read error, and the
-- frontend is untrusted regardless.
